apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "docker-registry.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
{{- if .Values.serviceAccount.enableIrsa }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaArn }}
{{- end }}
